### ISSUE TITLE
Replace system-filepath

### ISSUE THREAD

**Issue by PierreR** [Gabriella439/turtle#54] opened 2015-05-12 20:47 UTC
Any plan to drop system-filepath ?

It has been replaced by `filepath` in `wai` and is officially [deprecated](http://hackage.haskell.org/package/system-filepath-0.4.13.4).

**Comment by int-index** [comment] 2015-05-12 20:53
https://plus.google.com/+MichaelSnoyman/posts/Ft5hnPqpgEx

**Comment by Gabriel439** [comment] 2015-05-12 20:57
@PierreR What's the library that provides the new `FilePath` type you are referring to?

I don't mind switching off of the `system-filepath` type, though because it's poorly implemented.  It's inefficient and has lots of non-intuitive behaviors.

**Comment by PierreR** [comment] 2015-05-12 21:01
I meant the package [filepath](http://hackage.haskell.org/package/filepath) from ndmitchell

**Comment by Gabriel439** [comment] 2015-05-12 21:04
Alright, that sounds like a good idea, then.  I wasn't aware of the new `filepath` library but I'd like to keep `turtle` current with the best practices

**Comment by int-index** [comment] 2015-05-12 21:05
It has no separate `FilePath` type, though. And it works with `String`, not `Text`.

**Comment by Gabriel439** [comment] 2015-05-12 21:13
Oh, that's not acceptable either.

**Comment by PierreR** [comment] 2015-05-12 21:21
Well according to Neil it makes sense to keep FilePath as String ... That's what shake is doing.

I like Text myself but I have much less expertise ...

I would help me tremendously if the haskell community could agree on a common library to deal with filepath (i know it is not as easy as it sounds). Any advice on the matter is welcomed !

**Comment by Gabriel439** [comment] 2015-05-12 21:25
Maybe we can roll our own file path type.  We can actually make it more type safe in the process, by making it a category.  Here's an example of what I mean:

```haskell
{-# LANGUAGE GADTs #-}

import Data.Text

data Root
data Dir
data File

data Path a b where
    -- Most operations on a path are at the end of the path, so we store path components
    -- in reverse order for efficiency
    Nil       ::                         Path a a
    ConsRoot  ::         Path a Root  -> Path a Dir
    ConsDir   :: Text -> Path a Dir   -> Path a Dir
    ConsFile  :: Text -> Path a Dir   -> Path a File

instance Category Path where
    id  = Nil

    p1 . p2 = case p1 of
        Nil               -> p2
        ConsRoot      p1' -> ConsRoot      (p1' . p2)
        ConsDir   str p1' -> ConsDir   str (p1' . p2)
        ConsFile  str p1' -> ConsFile  str (p1' . p2)

instance IsString Path where ... -- Omitted

-- | Use `root` to anchor absolute paths
root :: Path Root Dir
root = ConsRoot Nil

-- | Create a path from a directory name
dir :: Text -> Path Dir Dir
dir str = ConsDir str Nil

-- | Create a path from a file name
file :: Text -> Path Dir File
file str = ConsFile str Nil
```

You can build a `Path` using the `IsString` instance if you want to keep the string syntax, but you can also build paths like this:

```haskell
dir "foo" >>> file "bar" :: Path Dir File
root >>> dir "foo" >>> file "bar" :: Path Root File
```

The idea is that you can tell from the type of the path whether it is absolute or relative and whether it is a file or directory:

```haskell
Path Root Dir  -- Absolute directory
Path Root File -- Absolute file
Path Dir  Dir  -- Relative directory
Path Dir  File -- Relative file
```

And composition prevents you from doing invalid things like concatenating two absolute paths or concatenating anything after a file.

**Comment by int-index** [comment] 2015-05-12 21:26
I like that idea a lot. I also feel that it should be a separate package.

**Comment by 3noch** [comment] 2015-05-12 21:31
Please do this, and then convince the rest of the Haskell community to use. We simply must take advantage of Haskell's type system or we are no better than Java.... :astonished:

**Comment by 3noch** [comment] 2015-05-12 21:33
I only worry that distinguishing between files and dirs in the type system might be very difficult.

**Comment by int-index** [comment] 2015-05-12 21:36
I don't think so. It's actually a very neat to distinguisg between them. We could even overload functions such as `mv` so that they would behave more like their Unix-counterparts! (For example, `mv file1 file2` renames the file and `mv file1 dir` puts it into a directory).

**Comment by Gabriel439** [comment] 2015-05-12 21:38
You can use polymorphism whenever you don't know what the start or end type should be:

```haskell
Path Root a  -- An absolute path to either a file or dir
Path Dir  a  -- A relative path to either a file or dir
Path a Dir   -- An absolute or relative path to a dir
Path a File  -- An absolute or relative path to a file
Path a b     -- This could be anything
```

In other words, a polymorphic type variable is analogous to "unknown".

In fact, there's a typo in my original code sample.  The `IsString` instance is supposed to be:

```haskell
instance IsString (Path a b) where ...
```

In other words, if you provide a `String` it will type-check as any sort of path by default.  The user can then opt in and refine the type if they want more checks.

**Comment by Gabriel439** [comment] 2015-05-12 21:38
I also agree that this should be a separate package

**Comment by Gabriel439** [comment] 2015-05-12 21:48
I also agree with @int-index .  If you have a function that you want to overload on multiple path types you can use a type class to do so.  This is what I've done for my internal projects.

**Comment by 3noch** [comment] 2015-05-12 21:50
Then I'm all in and will start using it as soon as it's on Hackage.

**Comment by 3noch** [comment] 2015-05-12 21:52
Recall that on Windows it's very easy to have many different "roots": UNC paths, drives, etc.

**Comment by Gabriel439** [comment] 2015-05-12 21:55
Yes, the full complexity of paths (like Windows) is the reason I have not released my internal path type as a package yet.

Let me put up the code I do have soon into a repository so other people can contribute.  I need to finish up a blog post first, so it might be a week before I organize what code I have.  Then other people can add things to that while I finish up my `annah` project.  After I finish `annah` (probably a few months from now) I can begin focusing on this in earnest.

**Comment by DanBurton** [comment] 2015-05-14 17:09
Note that @chrisdone has recently released a similar path abstraction.

http://hackage.haskell.org/package/path

**Comment by chrisdone** [comment] 2015-05-14 17:16
> I only worry that distinguishing between files and dirs in the type system might be very difficult in practice.

I've been internally using my path package for I guess the past 6 months on a few projects and it's really not a big deal in practice. You tend to know in advance what kind of paths you want to deal with, and this is both good documentation and a reasoning aid.

**Comment by 3noch** [comment] 2015-05-14 17:17
That's phenominal. I partly prefer @Gabriel439's `Root`/`Dir` distinction for the base over `Abs`/`Rel` because it seems more consistent and easier to customize different "roots".

**Comment by 3noch** [comment] 2015-05-14 17:18
@chrisdone But this is really good and I'll see if I can incorporate it.

**Comment by chrisdone** [comment] 2015-05-14 17:26
I'm not sure whether I prefer either, really. They both enumerate four use-cases. The `Category` instance is nice but in practice using Category's composition operator is a pain, I wish it'd been something else. It's the same reason I don't use it in `formatting`. 

``` haskell
Path Root Dir  -- Absolute directory
Path Root File -- Absolute file
Path Dir  Dir  -- Relative directory
Path Dir  File -- Relative file
```

Probably an argument in favour of `Abs`/`Rel` is that `Path Abs Dir` is self-explanatory and consistent with the plain English description; the comments aren't necessary. But the Category/Arrow instances are nice, so maybe we could just expose a `(</>)` = `Control.Category.(.)` operator for convenience.

I wouldn't go with allowing IsString instances; using validating TH QQ's has prevented bugs early for me. But for a scripting library like turtle you might want more convenient syntax.

I'm not big on the nested data structure representation but the internals are a detail.

**Comment by 3noch** [comment] 2015-05-14 17:37
Fair points. I suppose it's really just up to @Gabriel439 if he thinks the difference is worth a new lib.

> expose a (</>) = Control.Category.(.) operator for convenience.

Perfect.

**Comment by Gabriel439** [comment] 2015-05-14 18:35
@chrisdone So the advantages of `IsString` from `turtle`'s perspective are:

1.  Turtle tries to not be too much more verbose than the equivalent Unix commands
2.  One of the selling points of Turtle compared to other statically typed languages is the fast startup time of interpreted scripts

**Comment by Gabriel439** [comment] 2015-05-14 18:37
@chrisdone Oops, I forgot a third reason:

* Turtle tries to minimize boilerplate (this would require an additional `{-# LANGUAGE TemplateHaskell #-}` directive, although this point would be partially mitigated by the other open issue to provide a `/usr/bin/turtle`

**Comment by 3noch** [comment] 2015-05-14 18:51
@Gabriel439 I probably shouldn't mention that `path` currently uses `String` behind the scenes.

**Comment by Gabriel439** [comment] 2015-05-14 23:36
@chrisdone Actually, there's a fourth reason, which is that Turtle is also intended to be used interactively in `ghci`

**Comment by chrisdone** [comment] 2015-05-15 08:09
Yeah, it would be more ideal if OverloadedStrings expanded to `fromString :: String -> Q Exp` because the syntax is convenient.

**Comment by 3noch** [comment] 2015-05-15 17:01
Sounds like it's time for an `IsPath` typeclass.... :wink:

**Comment by int-index** [comment] 2015-05-18 01:43
@chrisdone That sounds like a great idea. Only instead of `Exp`, `TExp` should be used.

**Comment by Gabriel439** [comment] 2015-09-02 18:17
I just wanted to check in with an update on this issue.

So at this point it boils down to two competing alternatives:

**Alternative 1**: [The abstract `FilePath` proposal](https://ghc.haskell.org/trac/ghc/wiki/Proposal/AbstractFilePath)

This is basically a `newtype` around `FilePath`.  It's probably the least disruptive and it will interoperate well with the rest of the Haskell ecosystem.

**Alternative 2**: The `path` library

My main issue with the `path` library is the absence of the `IsString` instance.  If that was present I would immediately adopt `path`.

**Alternative 3**: The `path` library + an orphan `IsString` instance for `Path`

I've decided against releasing my own filepath library mainly because I don't want to fragment the filepath ecosystem further, especially when the `path` library is already so close to what I want.  I'd rather focus on persuading @chrisdone into adding an `IsString` instance for the `Path` type. :)

**Comment by chrisdone** [comment] 2015-09-02 18:34
I'm tempted to just expose `IsString` with some extra documentation elaborating on the advantages of smart constructors.

**Comment by chrisdone** [comment] 2015-09-02 19:14
Some thoughts:

* With instance `IsString (Path b t)` there's no way to know how to parse the string given into the correct type. So runtime validation isn't possible.
* To regain runtime validation, with, separate instances for `Path Abs File`, `Path Abs Dir`, etc. this makes type inference suck when `"foo"` is passed in parameter position to something accepting `Path b t`.
* `IsString` is effectively inviting users of my lib to make mistakes that could've been prevented at compile-time. Currently, if you have a `Path b t` value, it's valid. There's no "creeping in". Except with `Path.Internal`, which is explicitly I-take-responsibility-for-my-mistakes.
* Would a `Path.IsString` module be silly? It means people who want to make use of this syntax can explicitly choose to, but it wouldn't be part of the regular API.

**Comment by chrisdone** [comment] 2015-09-02 19:24
Leaning towards the `Path.IsString` module which turtle could simply import. Thoughts?

**Comment by Gabriel439** [comment] 2015-09-02 20:17
The problem with `Path.IsString` is that the type class instance will leak and make the instance available to unrelated modules.

However, I think the bigger issue is the one you mentioned about selecting the appropriate instance since the parsing behavior changes based on the type parameters.

There's also another issue that's a bit related, which is defining operations that work over a number of path types.  This usually requires introducing type classes over those operations.

I'll have to think about this some more.

**Comment by gregwebs** [comment] 2015-09-10 02:22
@Gabriel439 perhaps [data-filepath](https://github.com/mxswd/data-filepath) is more to your liking? I will try implementing path with Shelly.

**Comment by Gabriel439** [comment] 2015-09-10 03:22
Actually, I have an issue with both `path` and `data-filepath`, which is that the `Path` type in both libraries is not a category.  See the `Path` implementation I wrote up above for what I would expect to see for a typed `Path`.

**Comment by winterland1989** [comment] 2015-11-19 05:46
Is there really a big safety issue with `FilePath` as type synonym `String`?
As an user, i really don't understand this discussion anymore, safe is just one aspect of path manipulation, and `filepath` do provide means to guard against malformed path `String`s if you want to. If performance is an issue, i would argue that `String` is not that bad for most cases.

Really wish you guys don't give so many choices, now using multiple libraries became harder and harder.

**Comment by Gabriel439** [comment] 2015-11-19 16:18
Even if you eliminate all path manipulation errors there is still value in keeping it as a separate type to avoid accidentally providing a string where a function or utility expects a path.  `newtype`s also survive type inference and error messages, whereas type synonyms do not.

Let's use a simple example: the `writeFile` function from the `Prelude`.  If you swap the two arguments you will get a runtime error instead of a type error.  Also, if the user provides a `Bool` for the first argument instead of a `FilePath`, the error message communicates a misleading expected type:

```
    Couldn't match type `Bool' with `[Char]'
    Expected type: FilePath
      Actual type: Bool
    In the first argument of `writeFile', namely `True'
    In the expression: writeFile True "Contents"
    In an equation for `it': it = writeFile True "Contents"
```

... because type synonyms don't survive inference.

**Comment by winterland1989** [comment] 2015-11-19 16:48
I understand that newtype can help you mark same piece of data with different markers during type check, but the thing is how possibly someone pass a Bool to writeFile? Under what circumstances? 

AFAICT, path handling never became a serious problem in Java and JavaScript with all the holes on their type system, so basically I want to know the balance point between safety and convenience.

And I really want to use all these great libraries without importing tons of path handling stuff...

**Comment by Gabriel439** [comment] 2015-11-19 17:50
Note that you don't need to import tons of path handling stuff if you use `Turtle`.  It automatically re-exports path-handling utilities for you.

Path handling *is* an issue in Java.  I know because we've had several path manipulation bugs at Twitter in our Hadoop wrapper libraries that caused runtime errors.  I can't speak for Javascript because I don't use it very much.

> I understand that newtype can help you mark same piece of data with different markers during type check, but the thing is how possibly someone pass a Bool to writeFile? Under what circumstances?

If people always passed the correct type of argument to functions, we wouldn't need a static type system.

To answer your more general question about the balance between safety and convenience, the price you pay for a separate `FilePath` type is very low.  You can already use string literals to create `FilePath`s using the `OverloadedStrings` extension and `turtle` re-exports all the `FilePath` utilities you need, and there are utilities to convert easily back and forth between `String`s and `FilePath`s, so you incur very little extra verbosity for the extra type safety.

**Comment by winterland1989** [comment] 2015-11-20 00:45
Like you said, current system-filepath is OK to me with the help of OverloadedString, but it's deprecated. And that's why we discuss about replacement here, all I want to say is that filepath is not that bad.

Now suppose Turtle use Path, libA use system-filepath, and libB use filepath, I would say it's totally a mess to use them together. If somehow you still decided to create a new library, I don't know how this situation will become better.

**Comment by Gabriel439** [comment] 2015-11-20 00:48
I think a better solution would be to push this proposal through:

https://ghc.haskell.org/trac/ghc/wiki/Proposal/AbstractFilePath

I'm pretty firmly in favor of `FilePath` not being the same as `String`.

**Comment by winterland1989** [comment] 2015-11-20 02:22
That's exactly why I suggested to move to filepath library before that proposal is done, because everyone using filepath will get a clear migration path. But I'm aware lots of people are not satisfied with current String based filepath...

**Comment by winterland1989** [comment] 2015-11-20 02:24
Or maybe we should revamp system-filepath?

**Comment by Gabriel439** [comment] 2015-11-20 02:37
I don't think it's worth revamping `system-filepath`.  I'm fine with moving to `filepath` after the `Prelude` `FilePath` becomes an abstract type.  However, I don't want to have a regression in type safety by migrating to `filepath` ahead of time.

**Comment by bollu** [comment] 2015-12-27 11:57
Hey, I just started using `turtle`, and I was wondering what the status on this is!

**Comment by Gabriel439** [comment] 2015-12-27 17:15
At this point I'm waiting for somebody to pick up the `AbstractFilePath` proposal and push it over the finish line, and then I would switch to that.  I don't plan on using a filepath type that is a type synonym for `String` or `ByteString`.

In the meantime, the `system-filepath` library still works, even though it is deprecated.  If it really bothers people I could try to apply to maintain the library and move it out of deprecated status.

**Comment by bollu** [comment] 2015-12-27 19:38
Can I help with that? I'm not super experienced or anything, but I am
interested!

BTW, How can I help turtle evolve ? :) i would like to write some real
world Haskell code

**Comment by Gabriel439** [comment] 2015-12-27 19:41
The best place to begin for the `AbstractFilePath` proposal is here:

* https://ghc.haskell.org/trac/ghc/wiki/Proposal/AbstractFilePath

You can contact the original people who initiated that proposal and see what's the status of it and if there is any way to chip in.

As far as helping `turtle` specifically, feel free to submit pull requests for any utilities that you think might make your scripting life easier.

**Comment by LukeHoersten** [comment] 2016-10-20 20:35
Any updates here?

**Comment by 3noch** [comment] 2016-10-21 19:40
Perhaps Backback will get us far enough to move forward sooner rather than later.

**Comment by PierreR** [comment] 2016-12-19 15:04
FWIW bash users might be really surprised by this : 
```
userhome = "/home/vagrant"

readFoo = do
  ds <- input (userhome <> "/.foo")
  // eh eh eh 
  ...
```

**Comment by crocket** [comment] 2017-01-31 06:50
How do I convert `FilePath` to `String` or `Text` elegantly?
If I just used `show` on `FilePath`, I get `FilePath /path/to/something` instead of `/path/to/something`.

**Comment by PierreR** [comment] 2018-06-26 08:42
@Gabriel439 Are you still sticking to `system-filepath`now that the haskell community has moved on to `filepath` (https://packdeps.haskellers.com/reverse/filepath) ? 
FWIW I believe this is a real problem given that by nature `turtle` is expected to work well with the ecosystem ;-)

**Comment by Gabriel439** [comment] 2018-06-26 14:43
I'm still sticking to it. I still believe `FilePath`s should not be type synonyms for `String`.  Even a `newtype` would resolve my objections

**Comment by PierreR** [comment] 2018-06-26 16:47
I also believe `FilePath` should not be a type synonym for `String`.  Still IMHO in the context of `turtle`, `system-filepath` is  both error prone (#214) and  a real pain to use.

**Comment by Gabriel439** [comment] 2018-11-06 13:46
@ocharles: The main issue with that library is that it forbids an `IsString` instance for paths

**Comment by bfrk** [comment] 2020-05-01 10:28
A point that hasn't been mentioned in the discussion so far is that using `Text` as the underlying representation for (components of) paths makes it impossible to manipulate paths that are not valid unicode. This is an issue on Linux and other *nixes, which allow to use arbitrary byte sequences for path components (the only reserved bytes are `'/'` and `'\0'`). It is much less common nowadays to hit upon paths that are "invalid" according to the user's locale, but it cannot be ruled out either.
With `String` this is possible because of ghc's `getFileSystemEncoding` which gives you a PEP383 style variant of the locale encoding that uses lone surrogates to encode "invalid" bytes; which in turn allows to roundtrip back to the raw byte sequence.

**Comment by andreasabel** [comment] 2021-09-07 17:31
In the meantime, `Shelly` dropped `system-filepath`: https://github.com/gregwebs/Shelly.hs/commit/8288d27b93b57574135014d0888cf33f325f7c80#diff-bf44f7599a8d3e3ae0f9fa0626481c026bc4ea6cae608e1fd6b9dc7995ffef8b

**Comment by Gabriel439** [comment] 2021-09-15 04:46
Alright, I'll switch from `system-filepath` to the `FilePath` type from `base`.  It might take me some time (maybe a week?) to get to this, but in the meantime I would accept a pull request if somebody gets to this before I do

**Comment by hololeap** [comment] 2021-12-03 03:57
I have a patch partially created, and so far it hasn't been hard to replace `system-filepath` with `filepath`, but what about this big export list? Some of these functions don't have exact replacements in `filepath`.

https://github.com/Gabriel439/Haskell-Turtle-Library/blob/main/src/Turtle.hs#L123-L147

**Comment by Gabriel439** [comment] 2021-12-03 06:23
There are a few approaches I can think of:

* Approach 1: Don't worry about exact backwards compatibility and instead export a related set of utilities from `filepath` (as close as reasonably possible, not worrying about the names)

* Approach 2: Vendor the equivalent functions on the new `FilePath` within the `turtle` package, keeping the original names that `system-filepath` used

* Approach 3: Same as approach 2, except we drop support for any functions that might be tricky to implement exactly the same as `system-filepath`

I would probably suggest approach 3, but I would be fine with any of those three approaches

**Comment by jkachmar** [comment] 2022-05-02 19:07
Small note, but `text-2.0` is out and `system-filepath` has a restrictive upper bound on it.

It's probably not much  trouble to just bump the bounds there and add a Hackage revision, but the package _is_ deprecated, so I would understand if the maintainers had no interest in doing so.

**Comment by crocket** [comment] 2022-05-03 10:24
Would it be a hassle to just remove the upper bound or set the upper bound to a much higher number?

**Comment by Gabriella439** [comment] 2022-05-29 02:25
Alright, I have a fix up to remove the dependence on `system-file{path,io}` in favor of using the `FilePath` type from `base`: https://github.com/Gabriella439/turtle/pull/425

**Closed** 2022-06-06 19:47 UTC

**Comment by Gabriella439** [comment] 2022-06-06 21:50
I made several other changes along the way related to this:

* #427 
* #428 
* #429 

… and you can find the final CHANGELOG entry here:

https://github.com/Gabriella439/turtle/pull/430

… which I can summarize as: the post-1.6 API should be a drop-in replacement for the old API, but the CHANGELOG explains in more detail the ways that this can still break which are unavoidable no matter how many shims I add

I'll give people a week to test drive the changes and if nobody objects then I'll cut a release afterwards
